services:
  backend:
    build: ./backend
    container_name: backend_container
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=mongo_db
      - DB_USER=abdelrhman
      - DB_PASSWORD=123456
      - DB_NAME=my_db
      - DB_PORT=27017
    ports:
      - "5005:5000"
    depends_on:
      - mongo_db
    networks:
      - project_network

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - project_network

  mongo_db:
    image: mongo:4.4
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abdelrhman
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - mydata:/data/db
    networks:
      - project_network

volumes:
  mydata:

networks:
  project_network:
    driver: bridge
